### ISSUE TITLE
polea compile的时候出现报错

### ISSUE THREAD

**Issue by krapnikkk** [Hunterib/Laya-polea#1]
polea init也没有看到什么文件创建

polea compile的时候出现以下报错

` > error: Could not resolve "D:\\workspace\\AllModule_C\\.polea\\config.ts"

(node:15576) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
error: Could not resolve "D:\\workspace\\AllModule_C\\.polea\\config.ts"
    at failureErrorWithLog (C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:1449:15)
    at C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:1049:65)
    at buildResponseToResult (C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:1129:7)
    at C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:1236:14
    at C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (C:\Users\Admin\AppData\Roaming\nvm\v12.22.1\node_modules\polea\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
(node:15576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by Hunterib** [comment]
没有初始化项目 需要执行 polea init 这个命令，0.1.1之后的版本支持了 polea init 命令

**Comment by Hunterib** [comment]
请更新使用 npm i -g polea更新最新版本

**Comment by krapnikkk** [comment]
已经是最新版，查看了下源码，init中也没有看到调用什么方法

**Comment by Hunterib** [comment]
现在最新的版本是0.2.1，源码刚刚也更新了

**Comment by krapnikkk** [comment]
可以了，想了解一下是否有监听代码和资源文件自动更新的迭代计划呢？

**Comment by Hunterib** [comment]
有的，就只这两周
